### ISSUE TITLE
Regression in 0.8.0: build fails due to unconditional usage of `aligned_alloc`: `memoryManagement.c:48:28: error: implicit declaration of function 'aligned_alloc'`

### ISSUE THREAD

**Issue by barracuda156** [idris-lang/Idris2#3662]
```
/opt/local/var/macports/build/idris2-b99237ae/work/compwrap/cc/opt/local/bin/gcc-mp-14 -Os -arch ppc -Wall -fPIC -Wall -fPIC -Wall -fPIC -O2 -I/opt/local/include  -c -o memoryManagement.o memoryManagement.c
memoryManagement.c: In function 'idris2_newValue':
memoryManagement.c:48:28: error: implicit declaration of function 'aligned_alloc' [-Wimplicit-function-declaration]
   48 |   Value *retVal = (Value *)aligned_alloc(
      |                            ^~~~~~~~~~~~~
memoryManagement.c:6:1: note: include '<stdlib.h>' or provide a declaration of 'aligned_alloc'
    5 | #include "runtime.h"
  +++ |+#include <stdlib.h>
    6 | 
memoryManagement.c:48:28: warning: incompatible implicit declaration of built-in function 'aligned_alloc' [-Wbuiltin-declaration-mismatch]
   48 |   Value *retVal = (Value *)aligned_alloc(
      |                            ^~~~~~~~~~~~~
memoryManagement.c:48:28: note: include '<stdlib.h>' or provide a declaration of 'aligned_alloc'
make[2]: *** [memoryManagement.o] Error 1
make[2]: Leaving directory `/opt/local/var/macports/build/idris2-b99237ae/work/Idris2-0.8.0/support/refc'
make[1]: *** [build-refc] Error 2
```

`aligned_alloc` is not guaranteed to be available and should be checked at configure time.

**Comment by barracuda156** [comment]
@seagull-kamome FYI, this has been introduced by https://github.com/idris-lang/Idris2/commit/ddc634b1b251dbb94225818d68cd56b4e34bf523

C11 does not guarantee `aligned_alloc`, it is provided (or not) by the OS, not by the compiler.

**Comment by seagull-kamome** [comment]
Does adding the -std=c11 flag to gcc-mp-14 help resolve the issue?

**Comment by barracuda156** [comment]
@seagull-kamome No, it has nothing to do with the standard in discussed context, since it is not provided by the compiler. It is available only when the OS libs supply it, which is not the case for a lot of macOS versions. The first macOS to feature aligned_alloc is 10.15: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92143 

It is safer to use posix_memalign, which is supported back to 10.6 in macOS, or malloc, as the fallback here already does.
